import MiniEllipticPDE

open MiniEllipticPDE

def main : IO Unit := do
  IO.println "═══════════════════════════════════════════════════════"
  IO.println "  MiniEllipticPDE v0.1.0"
  IO.println "  Elliptic Partial Differential Equations"
  IO.println "  Geometric Analysis and PDE Theory"
  IO.println "═══════════════════════════════════════════════════════"
  IO.println ""
  IO.println "  Core Theory:"
  IO.println "    - RealField, NormedVectorSpace, InnerProductSpace"
  IO.println "    - HilbertSpace, BoundedLinearOperator, DualSpace"
  IO.println "    - Sobolev spaces: L2, H1, H01, H2 (abstract)"
  IO.println ""
  IO.println "  Elliptic Operators:"
  IO.println "    - Uniformly elliptic, strongly elliptic"
  IO.println "    - Bilinear forms: coercive, bounded, symmetric"
  IO.println "    - Divergence form, principal symbol"
  IO.println ""
  IO.println "  Fundamental Theorems:"
  IO.println "    - Lax-Milgram theorem (complete proof)"
  IO.println "    - Fredholm alternative (compact operators)"
  IO.println "    - Maximum principles (weak, strong, Hopf)"
  IO.println "    - Regularity theory (Caccioppoli, Schauder)"
  IO.println ""
  IO.println "  Methods:"
  IO.println "    - Energy methods (Dirichlet principle)"
  IO.println "    - Variational methods (mountain pass)"
  IO.println "    - Fixed point methods (Banach, Schauder)"
  IO.println "    - Compactness methods (Rellich-Kondrachov)"
  IO.println ""
  IO.println "  Examples (#eval):"
  IO.println "    - Laplace equation (Jacobi iteration)"
  IO.println "    - Poisson equation (Gauss-Seidel)"
  IO.println "    - Helmholtz equation (power iteration)"
  IO.println ""
  IO.println "  Applications:"
  IO.println "    - Geometry: harmonic maps, minimal surfaces, Yamabe"
  IO.println "    - Physics: electrostatics, quantum, elasticity"
  IO.println ""
  IO.println "  Advanced:"
  IO.println "    - Nonlinear: semilinear, quasilinear, fully nonlinear"
  IO.println "    - Higher regularity: De Giorgi-Nash-Moser, Krylov-Safonov"
  IO.println ""
  IO.println "  Frontiers:"
  IO.println "    - Fractional/nonlocal, homogenization, gauge theory"
  IO.println ""
  IO.println "  Depends on: mini-object-kernel"
  IO.println "  Run `lake build` to compile, `lake env lean --run Main.lean` for info."
